baseURL = "https://docs.blankdash.com/"
locale = "en-US"
title = "RTFM"
theme = "hextra"

enableRobotsTXT = true

[markup]
  [markup.highlight]
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# keep directory structure on publish
uglyURLs = false              # creates foo/bar/index.html, not foo/bar.html

[permalinks]
  default = "/:sections/:contentbasename/"
  authors = "/authors/:slug/"

[taxonomies]
  author = "authors"
  tag = "tags"